# Generated by Django 5.2.7 on 2025-10-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name for the stream', max_length=100)),
                ('url', models.URLField(help_text='HLS stream URL (.m3u8)')),
                ('description', models.TextField(blank=True, help_text='Optional stream info', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
