# Generated by Django 5.2.7 on 2025-12-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HTVConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(max_length=20, unique=True)),
                ('apn_name', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('update_rate', models.IntegerField(default=60)),
                ('can_type', models.CharField(choices=[('STDID', 'Standard'), ('EXTID', 'Extended')], default='STDID', max_length=10)),
                ('pid1', models.CharField(blank=True, max_length=4, null=True)),
                ('pid2', models.CharField(blank=True, max_length=4, null=True)),
                ('pid3', models.CharField(blank=True, max_length=4, null=True)),
                ('pid4', models.CharField(blank=True, max_length=4, null=True)),
                ('pid5', models.CharField(blank=True, max_length=4, null=True)),
                ('pid6', models.CharField(blank=True, max_length=4, null=True)),
                ('pid7', models.CharField(blank=True, max_length=4, null=True)),
                ('pid8', models.CharField(blank=True, max_length=4, null=True)),
                ('pid9', models.CharField(blank=True, max_length=4, null=True)),
                ('pid10', models.CharField(blank=True, max_length=4, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
